import java.nio.file.Files

plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'game.Main'
}

ext.lwjglVersion = "3.3.6"
ext.lwjglNatives = "natives-windows"

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-openal"
    implementation "org.lwjgl:lwjgl-opencl"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-stb"
    implementation "org.lwjgl:lwjgl::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-openal::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    implementation "org.lwjgl:lwjgl-stb::$lwjglNatives"

    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'
}

def ManifestTask(String taskName, String subStart, String subOutput, List<String> exts) {
    def startDir = file("src/main/resources/" + subStart)
    def outputFile = file("src/main/resources/" + subOutput)

    def task = tasks.register(taskName) {
        inputs.dir(startDir)
        outputs.file(outputFile)

        doLast {
            def lines = []
            Files.walk(startDir.toPath())
                    .filter {
                        def name = it.fileName.toString().toLowerCase()
                        Files.isRegularFile(it) && exts.any {ext -> name.endsWith(ext)}
                    }
                    .forEach {
                        lines.add(
                                startDir.toPath()
                                        .relativize(it)
                                        .toString()
                                        .replace("\\", "/")
                        )
                    }

            outputFile.text = lines.join("\n")
        }
    }

    return task
}

def textureManifest = ManifestTask(
        "textureManifest",
        "textures",
        "textures.manifest",
        [".png"]
)

def sfxManifest = ManifestTask(
        "sfxManifest",
        "audio/sfx",
        "sfx.manifest",
        [".wav"]
)

tasks.named("processResources") {
    dependsOn textureManifest
    dependsOn sfxManifest
}

tasks.jar {
    manifest {
        attributes(
                'Main-Class': 'game.Main'
        )
    }

    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}